### ISSUE TITLE
Translator does not work with bundler

### ISSUE THREAD

**Issue by shageman** [graysky/translator#11]
Hi,

I tried to use translator with bundler 0.8.1 and it install fine. However, I I get the following error, when doing calling rake (**bin/rake**, that is due to bundler...)
uninitialized constant ActionView::Helpers::TagHelper

And when running **gem exec script/server**:
/home/sh/evertango/vendor/bundler_gems/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:440:in `load_missing_constant': uninitialized constant ActionView::Helpers::TagHelper (NameError)

I'd love to fix this, but don't know where the dependency can be resolved. Any help is appreciated!

**Comment by graysky** [comment]
Thanks for the bug report. Can you tell me what I would have to do to reproduce this? I haven't played with bundler much yet.

**Comment by shageman** [comment]
I will try to reproduce it with a minimal setup. My quick attempt before work wasn't successful yet...

**Comment by shageman** [comment]
Sorry, I am unable to figure out why this is happening... Giving up for now. However, it is certainly not translator and bundler alone...

**Comment by graysky** [comment]
Okay. If you give me some more details about what you were doing / trying, I'd be happy to attempt it. Closing for now...

**Comment by shageman** [comment]
Using the newest bundler (0.9.1) made my problems go away...

**Comment by shageman** [comment]
Ok. Back to my old problem with bundler 0.9.7, but this time I can reproduce :) Here is what you do:

```
 gem install bundler --version '=0.9.7'
 git clone git://github.com/rails/rails.git
 cd rails
 git co v2.3.5
 cd ..
 ruby rails/railties/bin/rails new_app
 cd new_app
```

now, apply this patch to make the new_app use bundler and add some gems - including translator http://gist.github.com/308184 
we use bundler as intended:
     bundle install
     bundle lock

then this fails
     bundle exec script/server

with this error

```
 Error:
 => Booting WEBrick
 => Rails 2.3.5 application starting on http://0.0.0.0:3000
 /home/sh/.bundle/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:440:in `load_missing_constant': uninitialized constant     ActionView::Helpers::TagHelper (NameError)
from /home/sh/.bundle/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:80:in `const_missing'
from /home/sh/.bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_view/helpers/date_helper.rb:580
from /home/sh/.bundle/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
from /home/sh/.bundle/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
from /home/sh/.bundle/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:521:in `new_constants_in'
from /home/sh/.bundle/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
from /home/sh/.bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_view/helpers/form_helper.rb:2
from /home/sh/.bundle/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
from /home/sh/.bundle/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
from /home/sh/.bundle/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:521:in `new_constants_in'
from /home/sh/.bundle/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
from /home/sh/.bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_view/helpers/active_record_helper.rb:2
from /home/sh/.bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_view/helpers.rb:35
from /home/sh/.bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_view/helpers/tag_helper.rb:5
from /home/sh/.bundle/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
from /home/sh/.bundle/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
from /home/sh/.bundle/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:521:in `new_constants_in'
from /home/sh/.bundle/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
from /home/sh/.bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_view/helpers/translation_helper.rb:1
from /home/sh/.bundle/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
from /home/sh/.bundle/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
from /home/sh/.bundle/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:521:in `new_constants_in'
from /home/sh/.bundle/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
from /home/sh/.gem/ruby/1.8/gems/translator-1.0.0/lib/translator.rb:2
from /home/sh/workspace/testtranslator/.bundle/environment.rb:221:in `require'
from /home/sh/workspace/testtranslator/.bundle/environment.rb:221:in `require'
from /home/sh/workspace/testtranslator/.bundle/environment.rb:216:in `each'
from /home/sh/workspace/testtranslator/.bundle/environment.rb:216:in `require'
from /home/sh/workspace/testtranslator/.bundle/environment.rb:215:in `each'
from /home/sh/workspace/testtranslator/.bundle/environment.rb:215:in `require'
from /home/sh/workspace/testtranslator/config/boot.rb:120:in `load_environment'
from /home/sh/.bundle/ruby/1.8/gems/rails-2.3.5/lib/initializer.rb:137:in `process'
from /home/sh/.bundle/ruby/1.8/gems/rails-2.3.5/lib/initializer.rb:113:in `send'
from /home/sh/.bundle/ruby/1.8/gems/rails-2.3.5/lib/initializer.rb:113:in `run'
from /home/sh/workspace/testtranslator/config/environment.rb:9
from /home/sh/.bundle/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
from /home/sh/.bundle/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
from /home/sh/.bundle/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:521:in `new_constants_in'
from /home/sh/.bundle/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
from /home/sh/.bundle/ruby/1.8/gems/rails-2.3.5/lib/commands/server.rb:84
from script/server:3:in `require'
from script/server:3
```

If you comment out the translator gem in the Gemfile, the error goes away once you relock and try to start the server again.

I have the feeling that the dependency on rails (or some parts of it) are not properly resolved by bundler, because they are not specified in the gemspec. However, playing with it, I could not get it to work. I am thinking of something along the lines of  http://gist.github.com/308188

**Comment by jotero25** [comment]
have this been solve? I have the same problem when trying to use translator with bundle 1.0.0, rails 3.0 over ruby 1.9.2.
